### ISSUE TITLE
swift 5.4

### ISSUE THREAD

**Issue by justinmiller62** [wlisac/swift-on-balena#11]
Any plans to update this with swift 5.4 now that its available? 

https://github.com/uraimo/buildSwiftOnARM

**Comment by wlisac** [comment]
@justinmiller62 this would be fantastic, but I'm not sure of the status of Swift 5.4 for armv6 / armv7.

I took a quick look at https://github.com/uraimo/buildSwiftOnARM and it looks like the Swift 5.4 links aren't working.

I'm also not seeing any Swift 5.4 releases here: https://github.com/uraimo/buildSwiftOnARM/releases

Maybe @uraimo can provide some input on the status of Swift 5.4 and the empty links in the readme?
