### ISSUE TITLE
list supported versions

### ISSUE THREAD

**Issue by incanus** [wlisac/swift-on-balena#2]
It would be nice if you could list supported versions of Swift someplace. I was able to glean that the 4.2.x that you support is 4.2.3 by going [here](https://github.com/wlisac/swift-on-balena/tree/531aefda05d41dd2cc9872836652e0352f0f629d/Dockerfiles/device-base/generic-armv7ahf/debian/stretch) but it was non-obvious. 

I just wasn't up on what point release Swift 4.2 was at, is all.

**Comment by wlisac** [comment]
Makes sense and thanks for the feedback :)

I have a local branch where I'm generating the matrix of supported images (architecture / device / swift version / os version) to a markdown table. 

I think I should be able to merge that in soon and use it to generate a list of supported images.

**Comment by wlisac** [comment]
This is mostly addressed by https://github.com/wlisac/swift-on-balena/pull/3 by listing the supported Swift versions in the readme.

I'd still like to generate and show a full matrix of supported image variants in the future.
